name: HardcoreSurvival
version: 0.0.1
author: bistourimaisaussiunpeusuprequandmeme
main: fr.supre.hardcoresurvival.core.Main
api-version: 1.16
commands:
  revive:
    description: revive a dead player
  sacrifice:
    description: sacrfice yourself to spawn a totem
  tpto:
    description: teleport to a pleyr when you are dead
  start:
    description: start the game
  hardcorereload:
    description: reload the plugin